name: Spring boot ci

on:
  push:
    branches:
      - 'main'

jobs:
  validate_spring_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build maven and run tests
        run: mvn -B package --file pom.xml
